#!/usr/bin/perl
for (<>) {
	chomp;
	s/ *({|\/\/).*$//; # Remove line comment/opening brace
	if (/^(\w+ )+[*\w(\)]+\(.*\)[^=;]*$/) { # Function declaration
		s/(?<=[* ])\w+(?=[,)\[])//g; # Remove argument names
		s/ (?=[,)\[])//g; # Remove extra spaces
		print "$_;\n";
	}
}
