#!/usr/bin/tclsh
proc forrange {min max body} {
	uplevel 1 "for {set i $min} {\$i<$max} {incr i} {$body}"
}
forrange 30 38 {
	puts -nonewline "\033\[0;${i}m$i \033\[1mBold\033\[m "
}
puts "\033\[m"
forrange 90 98 {
	puts -nonewline "\033\[0;${i}m$i\033\[m "
}
puts "\033\[m"
proc 256coldemo {n} {
	puts -nonewline [format "\033\[48;5;${n}m%3d\033\[m " $n]
}
forrange 0 16 {
	256coldemo $i
}
puts "\033\[m"
forrange 16 232 {
	256coldemo $i
	if {($i-15)%36==0} {puts "\033\[m"}
}
forrange 232 256 {
	256coldemo $i
}
puts "\033\[m"
