#!/usr/bin/tclsh
array set seen [list]
foreach arg $argv {
	if [catch {regexp {^([0-9a-f]{32})} [exec md5sum $arg] -> sum} err] {
		puts $err
		continue
	}
	if [info exists seen($sum)] {
		puts "$arg is identical to $seen($sum)"
	} else {
		set seen($sum) $arg
	}
}
