#!/usr/bin/tclsh
foreach file $argv {
	if [catch {set fh [open $file r]}] {continue}
	puts "$file:"
	set l 1
	if [catch {set lines [split [read $fh] "\n"]} err] {
		puts $err
	}
	foreach line $lines {
		if {[string length $line]>80} {puts "$l: $line"}
		incr l
	}
	close $fh
}
