#!/usr/bin/tclsh
foreach file $argv {
	if [catch {set fh [open $file r]}] {continue}
	puts "$file:"
	set l 1
	foreach line [split [read $fh] "\n"] {
		if {[string length $line]>80} {puts "$l: $string"}
		incr l
	}
	close $fh
}
