#!/usr/bin/env tclsh
if [catch {set fh [open "/usr/share/dict/words" r]}] {
	error "No words file"
}
global w n
set w [split [read $fh] "\n"]
set n [llength $w]
close $fh
proc gw {{t 100}} {
	global w n
	for {} {$t>0} {incr t -1} {
		puts -nonewline "[lindex $w [expr {int(rand()*$n)}]] "
	}
}
gw {*}$argv
puts ""
