#!/usr/bin/env tclsh
lassign $argv prints wordfile
if {$wordfile eq ""} {set wordfile "/usr/share/dict/words"}
if {$prints eq ""} {set prints 40}

if [catch {set fh [open $wordfile r]}] {
	error "No words file"
}
set words [split [read $fh] "\n"]
close $fh

proc pick {l} {
	lindex $l [expr {int(rand()*[llength $l])}]
}
while {[incr prints -1] > 0} {
	puts -nonewline "[pick $words] "
}
puts ""
