#!/usr/bin/tclsh
lassign $argv keyword
foreach line [split [exec xinput --list] "\n"] {
	if [string match *$keyword* $line] {
		if ![regexp {id=(\d+)} $line => id] return
		puts $id
		catch {exec xinput --set-prop $id "Coordinate Transformation Matrix" \
			0.5 0 0 0 0.5 0 0 0 1}
		catch {exec xinput --set-prop $id "libinput Scroll Method Enabled" \
			0 0 1}
		catch {exec xinput --set-prop $id "Evdev Wheel Emulation" 1}
		catch {exec xinput --set-prop $id "Evdev Wheel Emulation Button" 2}
	}
}

