#!/usr/bin/tclsh
array set sgr_desc [list \
	"0" "Reset / Normal" \
	"1" "Bold or increased intensity" \
	"2" "Faint (decreased intensity)" \
	"3" "Italic" \
	"4" "Underline" \
	"5" "Slow Blink" \
	"6" "Rapid Blink" \
	"7" "Reverse video" \
	"8" "Conceal" \
	"9" "Crossed-out" \
	"20" "Fraktur" \
	"21" "Bold off" \
	"22" "Normal color or intensity" \
	"23" "Not italic, not Fraktur" \
	"24" "Underline off" \
	"25" "Blink off" \
	"27" "Inverse off" \
	"28" "Reveal" \
	"29" "Not crossed out" \
	"30" "Set foreground color" \
	"31" "Set foreground color" \
	"32" "Set foreground color" \
	"33" "Set foreground color" \
	"34" "Set foreground color" \
	"35" "Set foreground color" \
	"36" "Set foreground color" \
	"37" "Set foreground color" \
	"38" "Set foreground color" \
	"39" "Default foreground color" \
	"40" "Set background color" \
	"41" "Set background color" \
	"42" "Set background color" \
	"43" "Set background color" \
	"44" "Set background color" \
	"45" "Set background color" \
	"46" "Set background color" \
	"47" "Set background color" \
	"48" "Set background color" \
	"49" "Default background color" \
	"51" "Framed" \
	"52" "Encircled" \
	"53" "Overlined" \
	"54" "Not framed or encircled" \
	"55" "Not overlined" \
	"60" "ideogram underline or right side line" \
	"61" "ideogram double underline or double line on the right side" \
	"62" "ideogram overline or left side line" \
	"63" "ideogram double overline or double line on the left side" \
	"64" "ideogram stress marking" \
	"65" "ideogram attributes off" \
]
foreach arg $argv {puts "\033\[${arg}mExample\033\[m"}
if [llength $argv] exit
for {set n 0} {$n<=65} {incr n} {
	if [info exists sgr_desc($n)] {
		puts "$n: $sgr_desc($n) -- \033\[${n}mexample\033\[m"
	}
}
