#!/usr/bin/tclsh

set hist ~/Projects/utils/.shuffle_history

proc pick {l} {return [lindex $l [expr {int(rand()*[llength $l])}]]}
set lines [lrange [split [read stdin] "\n"] 0 end-1]
set choice [pick $lines]

if {![catch {set hist [open $hist a+]}]} {
	puts $hist $choice
	close $hist
}

exit [catch {exec -ignorestderr {*}$argv $choice}]
