#!/usr/bin/env tclsh
if {0} {
#	This script is a substitute for placing the following in ~/.tclshrc
	if {[lindex $argv 0] eq "-e"} {
		puts -nonewline [eval {*}[lrange $argv 1 end]]
		exit
	}
}
puts -nonewline [eval {*}$argv]
