#!/usr/bin/env perl
use strict;
use warnings;
my ($k,$i,$d)=@ARGV;
$k=$k x(length($i)/length($k)+1);
my @k = map ord,split //, $k;
my @i = map ord,split //, $i;
sub a ($) {$_[0]>=97?97:65}
sub l ($) {
	my ($l)=@_;
	return ($l>=65 && $l<=90)||($l>=97 && $l<=122)
}
sub e ($) {
	my ($k,$i)=@_;
	return chr(($i-a($i)+$k-a($k))%26+a($i));
}
sub d ($) {
	my ($k,$i)=@_;
	return chr(($i-a($i)-$k+a($k))%26+a($i));
}
my $f = $d?\&d:\&e;
while (@i) {
	my $i = shift @i;
	print l($i)?&$f(shift @k,$i):chr($i);
}
