export LANG=C
export LC_ALL=C
export SBCL_HOME=/usr/lib64/sbcl/
alias ls="ls --color=auto"
if [ -e ~/to-do ]; then
	echo -e "~/to-do :\n\n$( cat ~/to-do )\n"
else
	echo -e "Good news: no ~/to-do list!\n"
fi
# mount /mnt/MARKJOHNSON 2>/dev/null
# sleep 0.25 && startx && sleep 0.25 && logout
