set encoding=utf-8
set fileencoding=utf-8
set number
set mouse=a
set hlsearch
set undofile
set autoindent
set backup
set backupdir=~/.vim/tmp,.
set directory=~/.vim/tmp,.
filetype plugin indent on
syntax enable
if has("autocmd")
	  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif
