set encoding=utf-8
set fileencoding=utf-8
set number
set mouse=a
set hlsearch
set undofile
set autoindent
set backup
set incsearch
set noerrorbells
set undodir=~/.vim/tmp//,.
set backupdir=~/.vim/tmp//,.
set directory=~/.vim/tmp//,.
set background=light
filetype plugin indent on
syntax enable

au BufWinEnter * normal! `"

nnoremap <C-L> :nohlsearch<CR><C-L>
